#52 Set data-dtype for hp.temp and hp.tempmax to Number
ElfFriend-DnD/foundryvtt-compactBeyond5eSheet pull request #53
Opened 2021-06-01 12:00 UTC by CeaneC

Fixes #52

2021-06-01 12:58 UTC, akrigline requested changes

2021-06-01 12:58 UTC, akrigline commented on src/templates/parts/sheet-header.hbs
>              value="{{data.attributes.hp.temp}}" data-dtype="{{data.attributes.hp.type}}" />
I notice that the line below this sets `data-dtype` to `data.attributes.hp.type`. It looks like this is how the core system did this, but that changed 7 months ago. Can you remove this old declaration as part of this? Both inputs have it.

https://gitlab.com/foundrynet/dnd5e/-/commit/d03a2b51094fd629832f1fc39f17e729892f46da

2021-06-01 12:58 UTC, akrigline commented
Thanks for finding this and opening a PR! A quick cleanup of the old-bad-way and this is good to go.

2021-06-01 16:16 UTC, CeaneC commented on src/templates/parts/sheet-header.hbs
>              value="{{data.attributes.hp.temp}}" data-dtype="{{data.attributes.hp.type}}" />
Thanks for catching that, in my hastiness to fix the bug I didn't notice the second line

2021-06-26 15:22 UTC, akrigline commented
This completely slipped my mind... Sorry about that.

2021-06-26 15:22 UTC, merged